export const pageCopy = {
  header: {
    brandPrimary: 'Axi Docs',
    brandSecondary: 'Knowledge Hub',
    defaultContext: '知识总览',
    searchLabel: '搜索',
    searchPlaceholder: '搜索标签、标题或文档',
    commandSearchIdle: '搜索知识库',
  },
  home: {
    eyebrow: '知识关系图谱',
    title: '直接进入知识关系图谱',
    description: '首页只保留全局关系视图，先看节点、连接和分支，再决定是否进入分类导航或打开原文。',
    actionPrimary: '打开分类图谱',
    actionSecondary: '使用顶部搜索',
    commandLabel: '搜索知识库',
    commandPlaceholder: '搜索问题、组件、规范、ADR、排障记录',
    metrics: ['知识文档', '经验层级', '高频标签'],
    stageLabel: '关系主舞台',
    stageHint: '首页默认保留树状 3D 关系图谱。',
  },
  results: {
    eyebrow: '答案与证据',
    title: '答案候选与原文证据',
    idleTitle: '从经验分层进入证据阅读',
    description: '用更轻的工作台来承接搜索结果、经验分层和原文预览，不再和首屏图谱抢视线。',
  },
  category: {
    fallbackTitle: '分类图谱',
    fallbackDescription: '围绕当前分类聚焦查看核心节点、层级关系与关联知识点。',
    railTitle: '分类导航',
    railDescription: '左侧负责切换分类与入口，中间保留图谱舞台，节点详情改为按需展开。',
    nodeIntel: '节点情报',
    summaryTab: '关系摘要',
    previewTab: '原文预览',
    readingTab: '延伸阅读',
  },
  document: {
    description: '阅读完整文档内容，并沿着目录、相关节点与推荐路线继续深入。',
    toc: '目录锚点',
    related: '相关节点',
    intelligence: '文档情报',
    recommendations: '相关推荐',
  },
  graph: {
    loading: '构建知识图谱中...',
    emptyFocus: '先选择一篇文档，再进入聚焦图谱。',
    emptyFiltered: '当前筛选下没有可展示的节点。',
    heroPosterTitle: '知识关系舞台',
    heroPosterDescription: '优先稳定首屏结构，再在空闲时加载 3D 图谱。',
    heroMode: '主舞台',
    heroHint: '拖拽旋转，单击聚焦，双击打开证据',
    stageHint: '拖拽旋转，滚轮缩放，单击聚焦，双击打开证据',
    treePanel: '知识树抽屉',
    inspectorPanel: '节点情报',
    badges: {
      current: '当前文档',
      note: '知识文档',
      tag: '标签节点',
      branch: '树形分支',
    },
    labels: {
      focusEyebrow: '文档聚焦',
      globalEyebrow: '关系星图',
      treeEyebrow: '树形知识',
      orphanEyebrow: '孤岛雷达',
      focusTitle: '局部关系图',
      globalTitle: '全局知识图谱',
      treeTitle: '树形知识架构',
      orphanTitle: '孤岛知识分布',
      focusMode: '聚焦视图',
      treeMode: '树构视图',
      globalMode: '关系视图',
      orphanMode: '孤岛视图',
      documents: '文档',
      links: '连接',
      tags: '标签',
      orphans: '孤立',
      searchPlaceholder: '筛选路径 / 标签 / 文档名',
      tagsToggle: '标签层',
      rotateToggle: '自旋',
      clearBranch: '清除分支',
      rootView: '全库视图',
      looseDocs: '根文档',
      preview: '预览原文',
      open: '打开文档',
      filterByTag: '以此标签筛选',
      focusBranch: '聚焦该分支',
      inspectorEmpty: '点击一个节点查看路径、标签和快速操作。',
    },
  },
} as const
