name: Build and Trigger Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '10.7.1'  # 使用与你本地开发环境相同的 pnpm 版本

      # Install dependencies using pnpm
      - name: Install dependencies
        run: |
          pnpm install

      # Build VitePress project using pnpm
      - name: Build VitePress Project
        run: |
          pnpm run docs:build  # 使用 pnpm 执行 VitePress 构建命令

      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-axi-docs
          path: docs/.vitepress/dist/
          retention-days: 1

      # Expose build artifacts and trigger deployment
      - name: Expose build artifacts and trigger deployment
        run: |
          echo "BUILD_ARTIFACTS=$(pwd)/dist" >> $GITHUB_ENV
          echo "PROJECT_TYPE=vitepress" >> $GITHUB_ENV
          echo "DEPLOY_PATH=/www/wwwroot" >> $GITHUB_ENV

      # Trigger deployment workflow on Deployment Center
      - name: Trigger deployment workflow on Deployment Center
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DEPLOY_CENTER_PAT }}
          repository: MoseLu/axi-deploy  # 使用正确的仓库名称
          event-type: deploy
          client-payload: |
            {
              "project": "${{ github.repository }}",
              "deploy_path": "${{ env.DEPLOY_PATH }}",
              "run_id": "${{ github.run_id }}",
              "source_repo": "${{ github.repository }}",
              "nginx_config": "${{ secrets.NGINX_CONFIG }}",
              "nginx_path": "/etc/nginx/sites-available/${{ github.repository }}",
              "test_url": "http://your-website-url.com"
            }
