name: Test Permissions

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
      id-token: write
    
    steps:
      - name: 测试权限
        uses: actions/github-script@v7
        with:
          script: |
            try {
              console.log('测试权限...');
              console.log('当前仓库:', '${{ github.repository }}');
              console.log('目标仓库: MoseLu/axi-deploy');
              
              // 测试获取目标仓库信息
              const repoInfo = await github.rest.repos.get({
                owner: 'MoseLu',
                repo: 'axi-deploy'
              });
              console.log('✅ 可以访问目标仓库:', repoInfo.data.full_name);
              
              // 测试获取工作流信息
              const workflowInfo = await github.rest.actions.getWorkflow({
                owner: 'MoseLu',
                repo: 'axi-deploy',
                workflow_id: 'deploy-dispatch.yml'
              });
              console.log('✅ 可以访问目标工作流:', workflowInfo.data.name);
              
              console.log('✅ 权限测试通过');
            } catch (error) {
              console.error('❌ 权限测试失败:', error.message);
              console.error('错误详情:', error);
            } 