name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  test:
    uses: MoseLu/axi-deploy/.github/workflows/test-dispatch.yml@master
    with:
      caller_repo: '${{ github.repository }}'
      caller_branch: '${{ github.ref_name }}'
      caller_commit: '${{ github.sha }}' 